export default {
  GET_AUTH_TOKEN: 'GET_AUTH_TOKEN',
  GET_AUTH_TOKEN_FAILED: 'GET_AUTH_TOKEN_FAILED',

  REFRESH_AUTH_TOKEN: 'REFRESH_AUTH_TOKEN',
  REFRESH_AUTH_TOKEN_FAILED: 'REFRESH_AUTH_TOKEN_FAILED',

  GET_PORTFOLIOS: 'GET_PORTFOLIOS',
  GET_PORTFOLIOS_FAILED: 'GET_PORTFOLIOS_FAILED',

  GET_SELECTED_PORTFOLIO: 'GET_SELECTED_PORTFOLIO',
  GET_SELECTED_PORTFOLIO_FAILED: 'GET_SELECTED_PORTFOLIO_FAILED',

  DESELECT_SELECTED_PORTFOLIO: 'DESELECT_SELECTED_PORTFOLIO',
  DESELECT_SELECTED_PORTFOLIO_FAILED: 'DESELECT_SELECTED_PORTFOLIO_FAILED',
};
