export default {
  GET_AUTH_TOKEN: 'GET_AUTH_TOKEN',
  GET_AUTH_TOKEN_FAILED: 'GET_AUTH_TOKEN_FAILED',

  REFRESH_AUTH_TOKEN: 'REFRESH_AUTH_TOKEN',
  REFRESH_AUTH_TOKEN_FAILED: 'REFRESH_AUTH_TOKEN_FAILED',

  GET_PORTFOLIOS: 'GET_PORTFOLIOS',
  GET_PORTFOLIOS_FAILED: 'GET_PORTFOLIOS_FAILED',
};
